### ISSUE TITLE
WHERE IS REWRITE!?

### ISSUE THREAD

**Issue by LordoftheWild** [Pans-Pipes-Productions/Eternal-Forest#30]
Rewrite is apparently not the page I am looking for (404 error)

**Comment by LordoftheWild** [comment]
nevermind it's back now. I paniced

**Comment by Loquacious** [comment]
You cannot access branches through the GitHub pages. There was no problem. If you want to view it, just merge rewrite over and it will appear for the project page.

**Comment by LordoftheWild** [comment]
no I tried to switch to the rewrite branch using the drop-down and it gave me 404. but it works now. somehow...
